
version: "3.9"

services:
  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5000:5000"
"scripts": {
  "dev": "vite",
  "build": "vite build",
  "preview": "vite preview"
}
